# Generated by Django 4.1.3 on 2023-01-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bodytext',
        ),
        migrations.RemoveField(
            model_name='page',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='page',
            name='feedback',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='forenames',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='lastname',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
