# Generated by Django 4.1.3 on 2023-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_page_bodytext_remove_page_permalink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='page',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='forenames',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
